### ISSUE TITLE
Getting unsupported top level event type "onCast" dispatched

### ISSUE THREAD

**Issue by tara-singh-danu** [chaimPaneth/react-native-jw-media-player#164]
On Android when I tap on cast icon I get this message
"unsupported top level event type "onCast" dispatched"

"react-native-jw-media-player": "^0.2.3",
@chaimPaneth  Please check.

code at line no. 1003 in RNJWPalyerView.java
getReactContext().getJSModule(RCTEventEmitter.class).receiveEvent(getId(), "onCast", event);
creating this issue

**Comment by tara-singh-danu** [comment]
@chaimPaneth Please check...

**Comment by chaimPaneth** [comment]
This was fixed in latest versions.

**Comment by yksingh12** [comment]
@chaimPaneth I am getting the same error in the latest version of library 0.2.25. Can you please check again?

"Unsupported top level event type "onCasting" dispatched"

**Comment by yksingh12** [comment]
Replaced "onCasting" with "topCasting" to fix the crash in RNJWPlayerView.java file

getReactContext().getJSModule(RCTEventEmitter.class).receiveEvent(getId(), "topCasting", event);

**Comment by tauqeer13** [comment]
This issue is still there with the latest version of 0.2.26. Can you please fix that?

**Comment by chaimPaneth** [comment]
Merged on develop will be released on next version.
